version: '2'
services:
  zookeeper:
    image: arm64v8/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      ZOO_TICK_TIME: 40000
  kafka:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8888:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  db:
    image: arm64v8/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=miniominio
      - MINIO_ROOT_PASSWORD=miniominio
  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9016:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
